
import React, { useRef } from 'react';
import { QAItem } from '../types';
import { HelpCircleIcon, CopyIcon, SparklesIcon, PdfIcon } from './Icons';
import { jsPDF } from "jspdf";

interface QAModalProps {
  qa: QAItem[];
  refinedText: string;
  title: string;
  onClose: () => void;
  onCopy: (text: string) => void;
  onMigrateToNotebook: (content: string, title: string) => void;
}

const QAModal: React.FC<QAModalProps> = ({ qa, refinedText, title, onClose, onCopy, onMigrateToNotebook }) => {
  const pdfTemplateRef = useRef<HTMLDivElement>(null);
  const fullQAContent = qa.map((item, idx) => `Q${idx + 1}: ${item.question}\nA${idx + 1}: ${item.answer}`).join('\n\n');

  const handleDownloadPdf = async () => {
    const doc = new jsPDF({ orientation: 'p', unit: 'pt', format: 'letter' });
    const margin = 40;
    const safeTitle = title.replace(/[^a-z0-9]/gi, '_').toLowerCase();

    // Create a temporary container for PDF rendering to ensure it's well-formatted
    const element = document.createElement('div');
    element.style.width = '532pt'; // Letter width minus margins
    element.style.padding = '20pt';
    element.style.fontFamily = 'serif';
    element.style.color = '#000000';
    element.style.backgroundColor = '#ffffff';

    element.innerHTML = `
      <h1 style="font-size: 22pt; font-weight: bold; margin-bottom: 10pt; border-bottom: 1pt solid #000;">${title}</h1>
      <p style="font-size: 10pt; color: #666; margin-bottom: 20pt;">VoxScribe AI - Analysis & Q&A Report • ${new Date().toLocaleDateString()}</p>
      
      <h2 style="font-size: 16pt; font-weight: bold; margin-top: 20pt; margin-bottom: 10pt;">Refined Context</h2>
      <p style="font-size: 12pt; line-height: 1.5; font-style: italic; color: #333; margin-bottom: 20pt; padding: 10pt; border-left: 3pt solid #ccc; background: #f9f9f9;">
        ${refinedText}
      </p>
      
      <h2 style="font-size: 16pt; font-weight: bold; margin-top: 20pt; margin-bottom: 15pt;">Questions & Answers</h2>
      ${qa.map((item, idx) => `
        <div style="margin-bottom: 15pt; page-break-inside: avoid;">
          <p style="font-size: 12pt; font-weight: bold; margin-bottom: 4pt;">Q${idx + 1}: ${item.question}</p>
          <p style="font-size: 11pt; line-height: 1.4; color: #444;">A: ${item.answer}</p>
        </div>
      `).join('')}
      
      <div style="margin-top: 40pt; border-top: 0.5pt solid #eee; padding-top: 10pt; text-align: center; font-size: 9pt; color: #999;">
        Generated by VoxScribe AI - Professional Transcription Services
      </div>
    `;

    document.body.appendChild(element);

    try {
      await doc.html(element, {
        callback: (d) => {
          d.save(`VoxScribe_${safeTitle}_QA.pdf`);
          document.body.removeChild(element);
        },
        x: margin,
        y: margin,
        width: 532,
        windowWidth: 800
      });
    } catch (err) {
      console.error("PDF Generation Error:", err);
      document.body.removeChild(element);
    }
  };

  const handleMigrate = () => {
    const content = `
      <h1 style="font-size: 24pt; font-weight: bold; border-bottom: 2px solid #3b82f6; padding-bottom: 8px; margin-bottom: 16px;">${title} - Analysis & Q&A</h1>
      <h2 style="font-size: 18pt; font-weight: bold; color: #1e40af; margin-top: 24px;">Refined Text</h2>
      <p style="margin-bottom: 24px; color: #374151; font-style: italic; border-left: 4px solid #d1d5db; padding-left: 16px;">${refinedText}</p>
      <h2 style="font-size: 18pt; font-weight: bold; color: #1e40af; margin-top: 24px;">Questions & Answers</h2>
      ${qa.map((item, idx) => `
        <div style="margin-bottom: 16px; padding: 12px; background-color: #f8fafc; border-radius: 8px; border: 1px solid #e2e8f0;">
          <p style="font-weight: bold; color: #1e3a8a; margin-bottom: 4px;">Q: ${item.question}</p>
          <p style="color: #475569;">A: ${item.answer}</p>
        </div>
      `).join('')}
    `;
    onMigrateToNotebook(content, `${title} (Q&A)`);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/90 backdrop-blur-md">
      <div className="bg-slate-900 rounded-2xl w-full max-w-4xl max-h-[85vh] flex flex-col border border-slate-700 shadow-2xl overflow-hidden">
        <div className="p-6 border-b border-slate-700 flex justify-between items-center bg-slate-900">
          <div className="flex items-center space-x-3">
             <HelpCircleIcon className="w-6 h-6 text-blue-400" />
             <h2 className="text-2xl font-bold text-white">Analysis & Q&A</h2>
          </div>
          <div className="flex items-center space-x-3">
             <button 
                onClick={handleDownloadPdf}
                className="flex items-center space-x-2 bg-slate-800 hover:bg-slate-700 text-slate-300 px-4 py-2 rounded-lg text-sm font-medium transition-colors border border-slate-700"
                title="Download as PDF"
             >
                <PdfIcon className="w-4 h-4" />
                <span>Download PDF</span>
             </button>
             <button 
                onClick={handleMigrate}
                className="flex items-center space-x-2 bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors"
             >
                <SparklesIcon className="w-4 h-4" />
                <span>Save to Notebook</span>
             </button>
             <button onClick={onClose} className="text-slate-400 hover:text-white transition-colors p-1">
                <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" /></svg>
             </button>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-8 space-y-8 bg-slate-950">
          <div>
             <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-4">Refined Context</h3>
             <div className="p-5 bg-slate-900 border border-slate-800 rounded-xl text-slate-300 leading-relaxed italic">
                {refinedText}
             </div>
          </div>

          <div className="space-y-4">
             <div className="flex justify-between items-center">
                <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest">Inferred Q&A</h3>
                <button 
                   onClick={() => onCopy(fullQAContent)}
                   className="text-xs text-blue-400 hover:text-blue-300 flex items-center space-x-1"
                >
                   <CopyIcon className="w-3 h-3" />
                   <span>Copy All</span>
                </button>
             </div>
             <div className="space-y-4 pb-4">
                {qa.map((item, idx) => (
                   <div key={idx} className="bg-slate-900 border border-slate-800 rounded-xl p-5 hover:border-slate-700 transition-colors">
                      <p className="text-blue-400 font-bold mb-2 flex items-start">
                         <span className="mr-2 opacity-50 shrink-0">Q:</span>
                         <span>{item.question}</span>
                      </p>
                      <p className="text-slate-300 flex items-start">
                         <span className="mr-2 opacity-50 shrink-0">A:</span>
                         <span>{item.answer}</span>
                      </p>
                   </div>
                ))}
             </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default QAModal;
